### ISSUE TITLE
Module manifest data timed out, when trying to install module

### ISSUE THREAD

**Issue by Felian2** [Plushtoast/playlistenchantment#1]
Hi,

when I try to install the module in the fooundry interface, it always gives me the error message attached. Same when I copy the manifest URL from here. 
![Unbenannt](https://github.com/Plushtoast/playlistenchantment/assets/155839991/a506fbdb-0dc7-4f07-98ac-7c086373a798)

**Comment by Plushtoast** [comment]
Hi,
one of these things probably happened:

* Your internet connections was bad (can you install other modules)
* Github was offline, this happens in very rare cases. just try to install again at a later time

Make sure to try both install options:

* Module installer (recommended) 
![grafik](https://github.com/Plushtoast/playlistenchantment/assets/44941845/08562276-2c4d-4832-8cea-44a1a8bc090c)

* Manual install by adding this path: "https://raw.githubusercontent.com/Plushtoast/playlistenchantment/main/module.json"
![grafik](https://github.com/Plushtoast/playlistenchantment/assets/44941845/4e528fab-4e93-4bb1-ae9d-6748dc1f048b)

**Comment by Plushtoast** [comment]
Closed because of lacking feedback. Probably just internet hickup
